name: tests

on:
  push:
steps:
  - name: Set the value
    id: step_one
    run: |
      echo "UPSTREAM_BUILD_NUMBER = $((11581 + 5))" >> $GITHUB_ENV
  - name: Use the value
    id: step_two
    run: |
      echo "${{ UPSTREAM_BUILD_NUMBER }}" # This will output 'build number'
